const api_config = {
  //Development URL
  //BASE_URL: 'http://cottontradecentre.com/development/cotton_bid_v1/api/',
  BASE_URL: 'http://cottontradecentre.com/development/cotton_bid_v3/api/',
  //BASE_URL: 'http://cottontradecentre.com/development/cotton_bid_v1/api/',
  
  //Production URL
  //BASE_URL: 'http://cottontradecentre.com/cotton_bid/api/',

  //APIs Name
  SELLER_REGISTRATION: 'registration_buyer',
  GET_BUYER_TYPE: 'buyer_type',
  GET_BUSINESS_TYPE: 'business_type',
  GET_REGISTRATION_AS: 'registration_as',
  GET_STATE: 'state_list',
  GET_DISTRICT: 'district_list',
  GET_STATIONNAME: 'station_list',
  GET_CITY:'city_list',
  LOGIN_BUYER: 'login_buyer',
  RESEND_OTP: 'resend_otp_buyer',
  VERIFY_OTP: 'otp_verify_buyer',
  PRODUCT_LIST: 'product_list',
  PRODUCT_ATTRIBUTE_LIST: 'product_attribute_list',
  POST_TO_BUY: 'post_to_buy',
  MY_ACTIVE_POST:'notification_post_buy_list',
  COMPLETED_DEALS:'completed_deal_buyer',
  //COMPLETED_DEALS:'completed_deal_buyer_new_v2',
  CANCEL_POST:'cancel_post',
  LAB_LIST:'lab_list',
  FORGOT_PASSWORD_buyer:'forgot_password_buyer',
  RESET_PASSWORD_BUYER:'reset_password_buyer',
  //SEARCH_TO_BUY: 'search_to_buy',
  SEARCH_TO_BUY: 'search_to_buy_new',
  SEARCH_SELLER:'search_seller',
  NOTIFICATION_TO_SELLER:'notification_to_seller',
  NOTIFICATION_TO_SELLER_LIST: 'notification_to_seller_list',
  REGISTRATION_SCREEN_DROPDOWN_DATA:'sellertype_buyertype_businesstype_registrationas',
  NOTIFICATION_LIST:'notification_to_buy_list',
  //NEGOTIATION_LIST: 'negotiation_list_buyer',
  //NEGOTIATION_LIST: 'negotiation_list_buyer_new',
  NEGOTIATION_LIST: 'negotiation_list_buyer_new_v2',
  POST_DETAILS:'post_details',
  TRANSMIT_PAYMENT_LAB_LIST:'transmit_payment_lab_list',
  //NEGOTIATION: 'negotiation',
  NEGOTIATION: 'negotiation_new_v2',
  NEGOTIATION_DETAIL_OLD:'negotiation_detail',
  //MAKE_DEAL:'make_deal',
  MAKE_DEAL:'make_deal_new_v2',
  MY_CONTRACT:'my_contract',
  CHANGE_PASSWORD_BUYER: 'change_password_buyer',
  LOGOUT_BUYER: 'logout_buyer',
  CANCEL_NOTIFICATION:'cancel_notification',
  UPDATE_TRANSACTION_TRACKING: 'update_transaction_tracking',
  PROFILE_BUYER: 'profile_buyer',
  NEWS: 'news',
  NEWS_DETAIL: 'news_details',
  BROKER_LIST: 'broker_list_v1',
  NEGOTIATION_DETAIL:'negotiation_detail_new_v2',
  LAB_REPORT_STATUS:'lab_report_status',
  NEGOTIATION_DETAIL_BY_DEAL_NEW_V2:'negotiation_detail_by_deal_new_v2',
  EDIT_PROFILE_BUYER: 'edit_profile_buyer',
  ADD_BROKER_LIST: 'broker_list',
  SEARCH_BROKER: 'search_broker',
  ADD_BROKER:'add_broker',
  SEND_BROKER_REQUEST: 'send_broker_request',
  DELETE_BROKER:'delete_broker',
  PLAN_LIST: 'plan_list',
  CONTRACT_DETAIL:'contract_details',
  MAKE_DEAL_OTP_VERIFY:'make_deal_otp_verify',
  TRANSACTION_HISTORY:'transaction_history',
  RESEND_DEAL_OTP:'resend_deal_otp',
  ADD_USER_PLAN:'add_user_plan',
  GET_MCX_DATA: "get_mcx_data",
PARTY_WISE_CONTRACT_REPORT: 'party_wise_contract_report',
  PRODUCT_WISE_CONTRACT_REPORT: 'product_wise_contract_report',
  BROKER_WISE_CONTRACT_REPORT: 'broker_wise_contract_report',
  POST_REPORT : 'post_report',
  CONTRACT_PRODUCT_LIST : 'contract_product_list',
  CONTRACT_BROKER_LIST: 'contract_broker_list',
  CONTRACT_PARTY_LIST: 'contract_party_list'



  // nileshbavliya@gmail.com
};

export default api_config;
